// Code generated by goctl. DO NOT EDIT.
// Source: jobAgent.proto

package server

import (
	"context"

	"github.com/AdminAce-coder/jobAgent/internal/logic"
	"github.com/AdminAce-coder/jobAgent/internal/svc"
	"github.com/AdminAce-coder/jobAgent/pb/jobAgent"
)

type JobAgentServer struct {
	svcCtx *svc.ServiceContext
	jobAgent.UnimplementedJobAgentServer
}

func NewJobAgentServer(svcCtx *svc.ServiceContext) *JobAgentServer {
	return &JobAgentServer{
		svcCtx: svcCtx,
	}
}

func (s *JobAgentServer) DoJob(ctx context.Context, in *jobAgent.Request) (*jobAgent.Response, error) {
	l := logic.NewDoJobLogic(ctx, s.svcCtx)
	return l.DoJob(in)
}
