// Code generated by goctl. DO NOT EDIT.
// Source: jobAgent.proto

package jobagentclient

import (
	"context"

	"github.com/AdminAce-coder/jobAgent/pb/jobAgent"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = jobAgent.Request
	Response = jobAgent.Response

	JobAgent interface {
		DoJob(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultJobAgent struct {
		cli zrpc.Client
	}
)

func NewJobAgent(cli zrpc.Client) JobAgent {
	return &defaultJobAgent{
		cli: cli,
	}
}

func (m *defaultJobAgent) DoJob(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := jobAgent.NewJobAgentClient(m.cli.Conn())
	return client.DoJob(ctx, in, opts...)
}
